# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:
    semester_start: 2012-02-13
    semester_end: 2012-05-18
    calendar_timezone: Europe/Bratislava
    analytics_account: UA-21193959-1
