# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: timetable, action: homepage }

sf_guard_signin:
    url: /login
    param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
    url: /logout
    param: { module: sfGuardAuth, action: signout }

sf_guard_password:
    url: /request_password
    param: { module: sfGuardAuth, action: password }

# zobrazenie vsetkych hodin
lesson_list_all:
    url: /lesson/list
    param: { module: lesson, action: index }

lesson_search_all:
    url: /lesson/search
    param: { module: lesson, action: query }

timetable_show:
    url: /timetable/:id.:sf_format
    param: { module: timetable, action: show, sf_format: html }
    requirements:
        id: \d+
        sf_format: (?:html|txt|csv|ics)

timetable_new:
    url: /timetable/new
    param: { module: timetable, action: new }

timetable_create:
    url: /timetable
    param: { module: timetable, action: create }
    requirements:
        sf_method: post

timetable_change_lessons:
    url: /timetable/:id/change_lessons
    param: { module: timetable, action: changeLessons }
    requirements:
        sf_method: post

timetable_duplicate:
    url: /timetable/:id/duplicate
    param: { module: timetable, action: duplicate }
    requirements:
        sf_method: post

timetable_save:
    url: /timetable/:id/save
    param: { module: timetable, action: save }

timetable_delete:
    url: /timetable/:id/delete
    param: { module: timetable, action: delete }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
